name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Check if HelloWorld.java exists
      id: check-if-helloworld-java-exists
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Check if HelloWorld.java exists
        setup-command: chmod +x check_file.sh
        command: "./check_file.sh"
        timeout: 10
        max-score: 25
    - name: Validate HelloWorld.java
      id: validate-helloworld-java
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Validate HelloWorld.java
        setup-command: chmod +x run.sh
        command: "./run.sh"
        timeout: 10
        max-score: 75
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        CHECK-IF-HELLOWORLD-JAVA-EXISTS_RESULTS: "${{steps.check-if-helloworld-java-exists.outputs.result}}"
        VALIDATE-HELLOWORLD-JAVA_RESULTS: "${{steps.validate-helloworld-java.outputs.result}}"
      with:
        runners: check-if-helloworld-java-exists,validate-helloworld-java
